#!/usr/bin/env python3
"""Regenerates site/stdlib.html: `keal doc` (the standard library, from the
compiler's own signatures) re-dressed in the site's theme.

    python3 site/build-stdlib.py [path-to-keal]

Run it whenever the prelude changes; the page states its own provenance.
"""

import re
import subprocess
import sys

KEAL = sys.argv[1] if len(sys.argv) > 1 else "./target/release/keal"

raw = subprocess.run([KEAL, "doc"], capture_output=True, text=True, check=True).stdout

nav = re.search(r"<nav>(.*?)</nav>", raw, re.S).group(1)
main = re.search(r"<main>(.*?)</main>", raw, re.S).group(1)
# Drop kealdoc's own h1/subtitle/footer; the site page brings its own.
main = re.sub(r"<h1>.*?</h1>\s*<p>.*?</p>", "", main, count=1, flags=re.S)
main = re.sub(r"<footer>.*?</footer>", "", main, flags=re.S)

page = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Keal — The standard library</title>
<link rel="icon" type="image/png" href="assets/keal3.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="style.css">
<style>
/* kealdoc structure, in the site's clothes */
.sgrid { display: grid; grid-template-columns: 264px 1fr; min-height: 680px; }
.snav { border-right: 1px solid var(--line); padding: 20px 0 40px; position: sticky;
        top: 0; align-self: start; max-height: 100vh; overflow-y: auto; }
.snav .navmod { font: 600 11px 'JetBrains Mono', monospace; color: var(--faint);
                letter-spacing: .1em; text-transform: uppercase; padding: 4px 26px 10px; }
.snav a { display: block; padding: 5px 26px; font: 500 13px 'JetBrains Mono', monospace;
          color: var(--dim); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.snav a:hover { color: var(--ink); background: rgba(53,200,168,.06); }
.snav .k { display: inline-block; width: 52px; color: var(--faint); font-size: 11px; }
.smain { padding: 40px 52px 96px; max-width: 780px; }
.smain h1 { margin: 0 0 8px; font: 700 36px Sora, sans-serif; letter-spacing: -.015em; }
.smain .sub { margin: 0 0 8px; color: var(--dim); font: 400 15.5px/1.7 Sora, sans-serif; }
.smain h2 { font: 600 12px 'JetBrains Mono', monospace; color: var(--accent);
            letter-spacing: .08em; text-transform: uppercase; border-bottom: 1px solid var(--line);
            padding-bottom: 8px; margin: 44px 0 10px; }
.smain section { margin: 26px 0; }
.smain pre.sig { font: 13.5px/1.6 'JetBrains Mono', monospace; color: var(--mint);
                 background: var(--panel); border: 1px solid var(--line2);
                 padding: 10px 16px; border-radius: 8px; overflow-x: auto; margin: 0 0 8px; }
.smain pre.sig.m { background: none; border: 0; border-left: 3px solid var(--line2);
                   border-radius: 0; padding: 2px 16px; margin: 10px 0 4px; color: var(--code); }
.smain .members { margin-left: 14px; }
.smain p { margin: 6px 0; font: 400 14.5px/1.7 Sora, sans-serif; color: var(--prose); }
.smain code { font: 13px 'JetBrains Mono', monospace; color: var(--mint);
              background: rgba(53,200,168,.08); padding: 1px 5px; border-radius: 4px; }
</style>
</head>
<body>
<div class="wrap">

<nav class="nav">
  <div class="nav-left">
    <a href="index.html"><img class="nav-logo" src="assets/keal.png" alt="keal"></a>
    <div class="nav-links">
      <a href="docs.html" class="tab-active">Docs</a>
      <a href="tour.html">Tour</a>
      <span class="soon" title="Coming soon">Playground</span>
      <span class="soon" title="Coming soon">Blog</span>
    </div>
  </div>
  <div class="nav-right">
    <span class="badge">v0.5.0</span>
    <a class="btn-gh" href="https://github.com/geneacta/keal">GitHub</a>
  </div>
</nav>

<div class="sgrid">
  <div class="snav">
__NAV__
  </div>
  <div class="smain">
    <div class="crumb">Docs <span class="sl">/</span> Guide <span class="sl">/</span> <span class="here">Standard library</span></div>
    <h1>The standard library</h1>
    <p class="sub">Generated by <code>keal doc</code> from the prelude — the signatures below are the compiler's own. Operator traits, the three-valued <code>Comp</code>, lazy sequences, and the actor model, all written in Keal itself.</p>
__MAIN__
  </div>
</div>

</div>
<script src="site.js"></script>
</body>
</html>
"""

page = page.replace("__NAV__", nav).replace("__MAIN__", main)
open("site/stdlib.html", "w").write(page)
print("site/stdlib.html written")
