"""One page per language somebody might be arriving from.

Each entry is a mapping table — what you write there, what you write here
— plus the handful of things that will genuinely surprise you, which is
the part a syntax table cannot carry. Both languages, always.
"""

LANGS = [
    # ---------------------------------------------------------------- Java
    {
        "key": "java", "name": "Java", "blurb_en": "Classes without inheritance, null in the type system.",
        "blurb_fr": "Des classes sans héritage, null dans le système de types.",
        "intro_en": "Keal will feel close: static types, classes, generics, and a compiler that refuses what it cannot prove. The differences that matter are that nullability lives in the type, that there is no inheritance at all, and that a value's memory is counted rather than collected.",
        "intro_fr": "Keal vous semblera proche : types statiques, classes, génériques, et un compilateur qui refuse ce qu'il ne peut pas prouver. Les différences qui comptent : la nullité vit dans le type, il n'y a aucun héritage, et la mémoire d'une valeur est comptée plutôt que ramassée.",
        "rows": [
            ("Class with fields", "Classe avec champs", "class P { final int x; P(int x){this.x=x;} }", "record P(val x: Int)"),
            ("Mutable holder", "Objet mutable", "class C { int n; }", "class C(var n: Int)"),
            ("Nullable", "Nullable", "@Nullable String s;", "val s: String?"),
            ("Null check", "Test de nullité", "if (s != null) s.length()", "if (s != null) { s.length }"),
            ("Switch", "Switch", "switch (n) { case 0: … }", "when (n) { 0 -> … }"),
            ("Instance test", "Test d'instance", "if (o instanceof Circle c)", "when (o) { is Circle(r) -> … }"),
            ("Generic method", "Méthode générique", "<T> T first(List<T> xs)", "func first<T>(xs: List<T>): T"),
            ("Interface", "Interface", "interface Ord { int compareTo(…); }", "trait Ord { func compareTo(other: Self): Int }"),
            ("Lambda", "Lambda", "xs.stream().map(x -> x * 2)", "xs.map({ it * 2 })"),
            ("String format", "Formatage", '"hello " + name', '"hello ${name}"'),
            ("Destructor", "Destructeur", "AutoCloseable / try-with-resources", "proc deinit() { … }"),
        ],
        "notes": [
            ("No inheritance, and that is deliberate", "Pas d'héritage, et c'est délibéré",
             "There is no <code>extends</code>. Traits with default methods and composition cover the same ground without the diamond, and records cover the data classes. If your design leans on a base class, it becomes a trait plus a field.",
             "Il n'y a pas d'<code>extends</code>. Les traits à méthodes par défaut et la composition couvrent le même terrain sans le losange, et les records couvrent les classes de données. Si votre conception s'appuie sur une classe de base, elle devient un trait plus un champ."),
            ("Null is a type, not a value you fear", "Null est un type, pas une valeur à craindre",
             "<code>String</code> can never be null; <code>String?</code> can. The checker narrows an immutable binding after a test, so the cast Java makes you write is inferred.",
             "<code>String</code> ne peut jamais être null ; <code>String?</code> le peut. Le vérificateur rétrécit une liaison immuable après un test, si bien que le cast que Java vous fait écrire est déduit."),
            ("Memory is counted, and you can see it", "La mémoire est comptée, et vous pouvez la voir",
             "No collector, no pauses. <code>keal layout</code> prints every object's size and padding, <code>deinit</code> runs deterministically when the last reference dies, and a cycle is the one thing counting cannot free — write <code>weak</code> on the back edge.",
             "Pas de ramasse-miettes, pas de pauses. <code>keal layout</code> imprime la taille et le remplissage de chaque objet, <code>deinit</code> s'exécute de façon déterministe quand la dernière référence meurt, et un cycle est la seule chose que le comptage ne peut libérer — écrivez <code>weak</code> sur l'arête arrière."),
            ("You can still call Java", "Vous pouvez toujours appeler Java",
             "<code>import java.time.LocalDate</code> generates typed wrappers through JNI. The gateway is written in Keal; see the interop document.",
             "<code>import java.time.LocalDate</code> génère des enveloppes typées via JNI. La passerelle est écrite en Keal ; voyez le document d'interopérabilité."),
        ],
    },
    # -------------------------------------------------------------- Kotlin
    {
        "key": "kotlin", "name": "Kotlin", "blurb_en": "The closest relative — and where it parts ways.",
        "blurb_fr": "Le parent le plus proche — et là où il diverge.",
        "intro_en": "Keal borrowed Kotlin's shape on purpose: <code>val</code>/<code>var</code>, <code>?</code> in the type, <code>when</code>, smart casts, data classes, trailing-lambda ergonomics. What it did not borrow is the JVM, the extension functions, the coroutines, and the second way to say things.",
        "intro_fr": "Keal a emprunté la silhouette de Kotlin à dessein : <code>val</code>/<code>var</code>, le <code>?</code> dans le type, <code>when</code>, les smart casts, les data classes. Ce qu'il n'a pas emprunté : la JVM, les fonctions d'extension, les coroutines, et la seconde façon de dire les choses.",
        "rows": [
            ("Binding", "Liaison", "val x = 1", "val x = 1"),
            ("Data class", "Data class", "data class P(val x: Int)", "record P(val x: Int)"),
            ("Nullable", "Nullable", "val s: String? = null", "val s: String? = null"),
            ("Safe call", "Appel sûr", "s?.length", "s?.length"),
            ("Elvis", "Elvis", "s ?: \"d\"", "s ?: \"d\""),
            ("when", "when", "when (n) { 0 -> … }", "when (n) { 0 -> … }"),
            ("Function", "Fonction", "fun add(a: Int): Int = a", "func add(a: Int): Int { a }"),
            ("Unit function", "Fonction Unit", "fun log(s: String) { }", "proc log(s: String) { }"),
            ("Lambda", "Lambda", "xs.map { it * 2 }", "xs.map({ it * 2 })"),
            ("Interface", "Interface", "interface Ord", "trait Ord"),
            ("Coroutine", "Coroutine", "launch { … }", "sys.spawn({ self, msg -> … })"),
        ],
        "notes": [
            ("proc is the missing half of func", "proc est la moitié manquante de func",
             "Kotlin writes <code>fun f(): Unit</code>; Keal writes <code>proc f()</code> and refuses to let you use its non-result. <code>Unit</code> never appears in a program.",
             "Kotlin écrit <code>fun f(): Unit</code> ; Keal écrit <code>proc f()</code> et refuse qu'on utilise son non-résultat. <code>Unit</code> n'apparaît jamais dans un programme."),
            ("No extension functions, no operators by convention", "Ni fonctions d'extension, ni opérateurs par convention",
             "Operators come from eight traits (<code>Add</code>, <code>Ord</code>, …) that your type implements explicitly. There is one place to look for what <code>+</code> means.",
             "Les opérateurs viennent de huit traits (<code>Add</code>, <code>Ord</code>, …) que votre type implémente explicitement. Il y a un seul endroit où chercher ce que <code>+</code> veut dire."),
            ("Concurrency is actors, not coroutines", "La concurrence, ce sont des acteurs, pas des coroutines",
             "<code>spawn</code> a handler, <code>send</code> messages, <code>run</code>. Compiled natively each actor is an OS thread; the interpreters run a deterministic schedule, and both print the same bytes.",
             "<code>spawn</code> d'un gestionnaire, <code>send</code> de messages, <code>run</code>. Compilé nativement, chaque acteur est un thread système ; les interpréteurs exécutent un ordonnancement déterministe, et les deux impriment les mêmes octets."),
            ("Logic is spelled out", "La logique s'écrit en toutes lettres",
             "<code>and</code>, <code>or</code>, <code>not</code> — plus <code>xor</code>, <code>nand</code>, <code>nor</code>, <code>xnor</code> and <code>implies</code>, all at one precedence, so mixed expressions need parentheses.",
             "<code>and</code>, <code>or</code>, <code>not</code> — plus <code>xor</code>, <code>nand</code>, <code>nor</code>, <code>xnor</code> et <code>implies</code>, tous à une seule précédence : les expressions mixtes demandent des parenthèses."),
            ("So are the bits", "Les bits aussi",
             "<code>band</code>, <code>bor</code>, <code>bxor</code>, <code>bnot</code>, <code>shl</code>, <code>shr</code>, <code>ushr</code>. Kotlin spells them as infix words too; Keal adds that they mix with nothing without parentheses, and that they bind tighter than <code>==</code> — so <code>flag band 2 != 0</code> means what it looks like.",
             "<code>band</code>, <code>bor</code>, <code>bxor</code>, <code>bnot</code>, <code>shl</code>, <code>shr</code>, <code>ushr</code>. Kotlin les écrit aussi en toutes lettres ; Keal ajoute qu'ils ne se mélangent à rien sans parenthèses, et qu'ils lient plus fort que <code>==</code> — donc <code>flag band 2 != 0</code> veut dire ce qu'il a l'air de vouloir dire."),
        ],
    },
    # ------------------------------------------------------------------ Go
    {
        "key": "go", "name": "Go", "blurb_en": "Generics that monomorphise, errors that are not values.",
        "blurb_fr": "Des génériques monomorphisés, des erreurs qui ne sont pas des valeurs.",
        "intro_en": "Both languages are small on purpose and compile to native code. Keal differs in three big ways: nullability is in the type instead of every pointer being nil-able, generics compile to one copy per instantiation, and failure is a <code>throw</code> you catch rather than a second return value.",
        "intro_fr": "Les deux langages sont petits à dessein et compilent en natif. Keal diffère sur trois points : la nullité est dans le type au lieu que chaque pointeur soit nil-able, les génériques compilent vers une copie par instanciation, et l'échec est un <code>throw</code> qu'on attrape plutôt qu'une seconde valeur de retour.",
        "rows": [
            ("Binding", "Liaison", "x := 1", "val x = 1"),
            ("Mutable", "Mutable", "var x = 1", "var x = 1"),
            ("Struct", "Struct", "type P struct { X int }", "record P(val x: Int)"),
            ("Method", "Méthode", "func (p P) Len() int", "func length(): Int (inside the class)"),
            ("Interface", "Interface", "type Ord interface { … }", "trait Ord { … }"),
            ("Nil", "Nil", "var s *string = nil", "val s: String? = null"),
            ("Error", "Erreur", "v, err := f(); if err != nil", "try { f() } catch (e) { … }"),
            ("Slice", "Slice", "[]int{1, 2}", "[1, 2]"),
            ("Map", "Map", "map[string]int{\"a\": 1}", "{\"a\": 1}"),
            ("Goroutine", "Goroutine", "go work(ch)", "sys.spawn({ self, msg -> … })"),
            ("Switch", "Switch", "switch n { case 0: }", "when (n) { 0 -> … }"),
        ],
        "notes": [
            ("Errors are thrown, not returned", "Les erreurs sont lancées, pas retournées",
             "<code>throw \"…\"</code> and <code>try { } catch (e) { }</code>, on all three engines including native code — where it compiles to checked unwinding rather than to setjmp.",
             "<code>throw \"…\"</code> et <code>try { } catch (e) { }</code>, sur les trois moteurs y compris le code natif — où cela compile en déroulement vérifié plutôt qu'en setjmp."),
            ("Generics are monomorphised", "Les génériques sont monomorphisés",
             "One C function per instantiation, no boxing, no dictionary passing. <code>firstOr&lt;T&gt;</code> used at <code>Int</code> and <code>String</code> becomes two plain functions.",
             "Une fonction C par instanciation, sans boxing ni passage de dictionnaire. <code>firstOr&lt;T&gt;</code> utilisé en <code>Int</code> et <code>String</code> devient deux fonctions ordinaires."),
            ("Actors instead of channels", "Des acteurs au lieu de canaux",
             "There is no <code>select</code> and no channel type. An actor owns its state, messages are deep-copied on the way in, and the checker refuses a handler that reaches for shared mutable state.",
             "Il n'y a ni <code>select</code> ni type canal. Un acteur possède son état, les messages sont copiés en profondeur à l'entrée, et le vérificateur refuse un gestionnaire qui atteint un état mutable partagé."),
            ("Go is one link line away", "Go n'est qu'à une ligne d'édition de liens",
             "Build a Go package as a <code>c-archive</code> and hand it to <code>keal build</code>; the example in the repository does exactly that.",
             "Compilez un paquet Go en <code>c-archive</code> et passez-le à <code>keal build</code> ; l'exemple du dépôt fait exactement cela."),
        ],
    },
    # ---------------------------------------------------------------- Rust
    {
        "key": "rust", "name": "Rust", "blurb_en": "Counting instead of borrowing, and why.",
        "blurb_fr": "Compter plutôt qu'emprunter, et pourquoi.",
        "intro_en": "The toolchain is written in Rust, so the debt is acknowledged. But Keal made the opposite memory trade: reference counting with a documented model instead of a borrow checker. You give up compile-time aliasing guarantees; you get a language with no lifetimes to write.",
        "intro_fr": "La chaîne d'outils est écrite en Rust, la dette est donc reconnue. Mais Keal a fait le choix mémoire inverse : comptage de références au modèle documenté plutôt qu'un vérificateur d'emprunts. On renonce aux garanties d'aliasing à la compilation ; on gagne un langage sans durées de vie à écrire.",
        "rows": [
            ("Binding", "Liaison", "let x = 1;", "val x = 1"),
            ("Mutable", "Mutable", "let mut x = 1;", "var x = 1"),
            ("Struct", "Struct", "struct P { x: f64 }", "record P(val x: Float)"),
            ("Option", "Option", "Option<String>", "String?"),
            ("Unwrap or default", "Unwrap ou défaut", "opt.unwrap_or(d)", "opt ?: d"),
            ("Match", "Match", "match n { 0 => … }", "when (n) { 0 -> … }"),
            ("Trait bound", "Borne de trait", "fn f<T: Ord>(x: T)", "func f<T: Ord>(x: T)"),
            ("Closure", "Fermeture", "|x| x * 2", "{ x -> x * 2 }"),
            ("Result", "Result", "Result<T, E> + ?", "try { } catch (e) { }"),
            ("Rc / Weak", "Rc / Weak", "Rc<T> / Weak<T>", "the default / weak var f: T?"),
            ("Threads", "Threads", "std::thread::spawn", "sys.spawn({ self, msg -> … })"),
        ],
        "notes": [
            ("No lifetimes, no borrow checker", "Ni durées de vie, ni vérificateur d'emprunts",
             "Every heap value is counted, as if everything were <code>Rc</code>. Assignment shares; there is no move semantics to reason about, and nothing to annotate.",
             "Chaque valeur du tas est comptée, comme si tout était <code>Rc</code>. L'affectation partage ; il n'y a pas de sémantique de déplacement à raisonner, ni rien à annoter."),
            ("weak is the same idea you already know", "weak est l'idée que vous connaissez déjà",
             "A cycle is the one thing counting cannot free, and <code>weak var</code> is <code>Weak&lt;T&gt;</code> with the upgrade done for you: reading gives the target while it lives, <code>null</code> after.",
             "Un cycle est la seule chose que le comptage ne peut libérer, et <code>weak var</code> est <code>Weak&lt;T&gt;</code> avec l'upgrade fait pour vous : la lecture donne la cible tant qu'elle vit, <code>null</code> ensuite."),
            ("Errors unwind rather than propagate", "Les erreurs déroulent au lieu de se propager",
             "There is no <code>?</code> operator and no <code>Result</code>: a failure throws, and <code>catch</code> binds the message. Integer overflow panics in release builds too.",
             "Il n'y a ni opérateur <code>?</code> ni <code>Result</code> : un échec lance, et <code>catch</code> lie le message. Le débordement entier panique aussi en compilation optimisée."),
            ("Rust libraries link straight in", "Les bibliothèques Rust s'éditent de liens directement",
             "Build a <code>staticlib</code>, declare the symbols with <code>extern func</code>, pass the <code>.a</code> to <code>keal build</code>.",
             "Compilez une <code>staticlib</code>, déclarez les symboles avec <code>extern func</code>, passez le <code>.a</code> à <code>keal build</code>."),
        ],
    },
    # ------------------------------------------------------------------- C
    {
        "key": "c", "name": "C", "blurb_en": "The same machine, with the footguns removed.",
        "blurb_fr": "La même machine, sans les pièges.",
        "intro_en": "Keal compiles <em>to</em> C11, so what you know about the machine still holds — layout, the ABI, the linker. What changes is that bounds are checked, integers do not wrap silently, memory is freed for you, and the type system knows which pointers can be null.",
        "intro_fr": "Keal compile <em>vers</em> C11 : ce que vous savez de la machine reste vrai — disposition mémoire, ABI, éditeur de liens. Ce qui change : les bornes sont vérifiées, les entiers ne débordent pas en silence, la mémoire est libérée pour vous, et le système de types sait quels pointeurs peuvent être nuls.",
        "rows": [
            ("Variable", "Variable", "int x = 1;", "var x = 1"),
            ("Constant", "Constante", "const int x = 1;", "val x = 1"),
            ("Struct", "Struct", "struct P { double x; };", "record P(val x: Float)"),
            ("Pointer that may be null", "Pointeur nullable", "char *s = NULL;", "val s: String? = null"),
            ("Array", "Tableau", "int a[] = {1, 2};", "val a = [1, 2]"),
            ("Loop", "Boucle", "for (int i=0;i<3;i++)", "for (i in 0..3)"),
            ("Switch", "Switch", "switch (n) { case 0: … break; }", "when (n) { 0 -> … }"),
            ("Function pointer", "Pointeur de fonction", "int (*f)(int)", "val f: (Int) -> Int"),
            ("malloc / free", "malloc / free", "malloc / free", "counted automatically"),
            ("Header", "En-tête", "extern int f(int);", "extern func f(x: Int): Int = \"f\""),
            ("Inline C", "C en ligne", "—", "native \"\"\" … \"\"\""),
        ],
        "notes": [
            ("You can read the C it emits", "Vous pouvez lire le C qu'il produit",
             "<code>keal emit-c f.keal</code> prints one self-contained translation unit, runtime included. Nothing is hidden, and <code>keal layout</code> prints every struct's offsets and padding.",
             "<code>keal emit-c f.keal</code> imprime une unité de traduction autonome, runtime compris. Rien n'est caché, et <code>keal layout</code> imprime les décalages et le remplissage de chaque struct."),
            ("Checked where C is silent", "Vérifié là où C se tait",
             "Integer overflow, division by zero and out-of-bounds indexing panic with a message and a line, on every engine — rather than being undefined.",
             "Débordement entier, division par zéro et indexation hors bornes paniquent avec un message et une ligne, sur tous les moteurs — au lieu d'être indéfinis."),
            ("Ownership at the boundary is written down", "La propriété à la frontière est écrite",
             "A <code>String</code> crossing to C says <code>borrow</code> or <code>own</code>; records cross by copy as headerless mirror structs. The checker refuses anything whose lifetime it cannot state.",
             "Une <code>String</code> qui passe vers C dit <code>borrow</code> ou <code>own</code> ; les records passent par copie sous forme de structs miroirs sans en-tête. Le vérificateur refuse ce dont il ne peut énoncer la durée de vie."),
            ("Cycles are the one leak left", "Les cycles sont la seule fuite restante",
             "Counting frees everything but a cycle. Write <code>weak</code> on the back edge and it dies like anything else.",
             "Le comptage libère tout sauf un cycle. Écrivez <code>weak</code> sur l'arête arrière et il meurt comme le reste."),
        ],
    },
    # ----------------------------------------------------------------- C++
    {
        "key": "cpp", "name": "C++", "blurb_en": "RAII you already understand, without the rest.",
        "blurb_fr": "Le RAII que vous connaissez, sans le reste.",
        "intro_en": "If you write modern C++, most of Keal's memory model is familiar: <code>shared_ptr</code> everywhere, <code>weak_ptr</code> for cycles, destructors that run deterministically. What is gone is the rest of the surface — no templates to instantiate by hand, no overload resolution, no headers, no undefined behaviour.",
        "intro_fr": "Si vous écrivez du C++ moderne, l'essentiel du modèle mémoire de Keal vous est familier : <code>shared_ptr</code> partout, <code>weak_ptr</code> pour les cycles, des destructeurs déterministes. Ce qui disparaît, c'est le reste de la surface — pas de templates à instancier à la main, pas de résolution de surcharge, pas d'en-têtes, pas de comportement indéfini.",
        "rows": [
            ("Shared object", "Objet partagé", "shared_ptr<T>", "the default"),
            ("Weak reference", "Référence faible", "weak_ptr<T>", "weak var f: T?"),
            ("Destructor", "Destructeur", "~T() { }", "proc deinit() { }"),
            ("Value struct", "Struct valeur", "struct P { double x; };", "record P(val x: Float)"),
            ("Template", "Template", "template<class T> T f(T)", "func f<T>(x: T): T"),
            ("Concept", "Concept", "template<Ord T>", "func f<T: Ord>(x: T)"),
            ("Optional", "Optionnel", "std::optional<T>", "T?"),
            ("Lambda", "Lambda", "[&](int x){ return x*2; }", "{ x -> x * 2 }"),
            ("Exception", "Exception", "throw / catch", "throw / catch"),
            ("Operator overload", "Surcharge d'opérateur", "operator+", "trait Add"),
            ("Namespace", "Espace de noms", "namespace a { }", "one flat namespace, for now"),
        ],
        "notes": [
            ("Templates without the instantiation errors", "Des templates sans les erreurs d'instanciation",
             "Generics are checked once at the declaration, then monomorphised. A generic that type-checks compiles at every instantiation — no pages of errors from inside a header.",
             "Les génériques sont vérifiés une fois à la déclaration, puis monomorphisés. Un générique qui typecheck compile à chaque instanciation — pas de pages d'erreurs venues d'un en-tête."),
            ("No overloading, one name one meaning", "Pas de surcharge, un nom un sens",
             "Operators come from traits, and a name means one thing in a scope. It costs some expressiveness and buys back the ability to read a call site.",
             "Les opérateurs viennent des traits, et un nom veut dire une chose dans une portée. Cela coûte un peu d'expressivité et rend la lecture d'un site d'appel possible."),
            ("C++ links in directly", "Le C++ s'édite de liens directement",
             "Pass a <code>.cpp</code> on the <code>keal build</code> line: it compiles under <code>c++</code>, the generated C stays C11, and only the link is shared.",
             "Passez un <code>.cpp</code> sur la ligne <code>keal build</code> : il compile sous <code>c++</code>, le C généré reste C11, et seul l'édition de liens est partagée."),
            ("Deterministic, still", "Déterministe, toujours",
             "<code>deinit</code> runs at the next statement boundary, youngest first — the same order a stack of RAII objects unwinds in.",
             "<code>deinit</code> s'exécute à la frontière d'instruction suivante, le plus jeune d'abord — l'ordre même où une pile d'objets RAII se déroule."),
        ],
    },
    # ------------------------------------------------------------------ C#
    {
        "key": "csharp", "name": "C#", "blurb_en": "Nullable reference types, taken all the way.",
        "blurb_fr": "Les types référence nullables, poussés jusqu'au bout.",
        "intro_en": "C#'s nullable reference types are opt-in and warn; in Keal they are the type system and they refuse. Beyond that: no inheritance, no properties, no LINQ — but records, pattern matching and string interpolation will all feel like home.",
        "intro_fr": "Les types référence nullables de C# sont optionnels et avertissent ; en Keal ils sont le système de types et ils refusent. Au-delà : pas d'héritage, pas de propriétés, pas de LINQ — mais les records, le filtrage par motifs et l'interpolation de chaînes vous sembleront familiers.",
        "rows": [
            ("Record", "Record", "record P(double X);", "record P(val x: Float)"),
            ("Class", "Classe", "class C { int N { get; set; } }", "class C(var n: Int)"),
            ("Nullable", "Nullable", "string? s", "val s: String?"),
            ("Null-coalescing", "Coalescence", "s ?? \"d\"", "s ?: \"d\""),
            ("Null-conditional", "Accès conditionnel", "s?.Length", "s?.length"),
            ("Pattern switch", "Switch à motifs", "n switch { 0 => … }", "when (n) { 0 -> … }"),
            ("Type pattern", "Motif de type", "if (o is Circle c)", "when (o) { is Circle(r) -> … }"),
            ("Generic", "Générique", "T First<T>(List<T> xs)", "func first<T>(xs: List<T>): T"),
            ("Interface", "Interface", "interface IOrd", "trait Ord"),
            ("Interpolation", "Interpolation", "$\"hello {name}\"", "\"hello ${name}\""),
            ("Async", "Async", "async Task<T> / await", "actors: spawn / send / run"),
        ],
        "notes": [
            ("Nullability refuses, it does not warn", "La nullité refuse, elle n'avertit pas",
             "<code>String</code> and <code>String?</code> are different types, always, with no flag to turn it off and no annotation to forget.",
             "<code>String</code> et <code>String?</code> sont des types différents, toujours, sans option pour désactiver ni annotation à oublier."),
            ("No properties, no hidden work", "Pas de propriétés, pas de travail caché",
             "A field access is a field access. If something computes, it is a method and it has parentheses.",
             "Un accès de champ est un accès de champ. Si quelque chose calcule, c'est une méthode et elle a des parenthèses."),
            ("No LINQ, but the methods are there", "Pas de LINQ, mais les méthodes sont là",
             "<code>map</code>, <code>filter</code>, <code>fold</code>, and a lazy <code>Sequence</code> pipeline written in Keal itself — nothing runs until a terminal operation pulls.",
             "<code>map</code>, <code>filter</code>, <code>fold</code>, et un pipeline paresseux <code>Sequence</code> écrit en Keal — rien ne s'exécute avant qu'une opération terminale ne tire."),
            ("No runtime to install", "Aucun runtime à installer",
             "<code>keal build</code> produces a native executable with no VM under it, and the compiler itself has zero dependencies.",
             "<code>keal build</code> produit un exécutable natif sans machine virtuelle dessous, et le compilateur lui-même n'a aucune dépendance."),
        ],
    },
    # -------------------------------------------------------------- Python
    {
        "key": "python", "name": "Python", "blurb_en": "The same readability, checked before it runs.",
        "blurb_fr": "La même lisibilité, vérifiée avant l'exécution.",
        "intro_en": "The biggest change is that everything is checked before it runs, and types are not optional hints. The second biggest is that indentation carries no meaning — blocks are braces. What survives: readable code, interpolation, list and map literals, and a REPL.",
        "intro_fr": "Le plus grand changement : tout est vérifié avant l'exécution, et les types ne sont pas des indications facultatives. Le deuxième : l'indentation ne signifie rien — les blocs sont des accolades. Ce qui survit : du code lisible, l'interpolation, les littéraux de listes et de maps, et un REPL.",
        "rows": [
            ("Binding", "Liaison", "x = 1", "val x = 1"),
            ("Rebindable", "Réaffectable", "x = 1; x = 2", "var x = 1"),
            ("Function", "Fonction", "def add(a, b): return a + b", "func add(a: Int, b: Int): Int { a + b }"),
            ("No return", "Sans retour", "def log(s): print(s)", "proc log(s: String) { println(s) }"),
            ("List", "Liste", "[1, 2]", "[1, 2]"),
            ("Dict", "Dictionnaire", "{\"a\": 1}", "{\"a\": 1}"),
            ("f-string", "f-string", "f\"hello {name}\"", "\"hello ${name}\""),
            ("None", "None", "x = None", "val x: String? = null"),
            ("Class", "Classe", "class C: def __init__(self, n)", "class C(var n: Int)"),
            ("Dataclass", "Dataclass", "@dataclass class P: x: float", "record P(val x: Float)"),
            ("Comprehension", "Compréhension", "[x*2 for x in xs]", "xs.map({ it * 2 })"),
        ],
        "notes": [
            ("Types are not hints", "Les types ne sont pas des indications",
             "You annotate parameters and fields; everything else is inferred. A mismatch is an error before the program starts, not a surprise on line 400.",
             "Vous annotez les paramètres et les champs ; le reste est déduit. Une incompatibilité est une erreur avant le démarrage, pas une surprise à la ligne 400."),
            ("There is no self", "Il n'y a pas de self",
             "Methods take no receiver parameter — <code>this</code> is available inside a class, and that is all. (In actor handlers you may see a parameter <em>named</em> <code>self</code>; it is a name the author chose, not a keyword.)",
             "Les méthodes ne prennent pas de paramètre receveur — <code>this</code> est disponible dans une classe, et c'est tout. (Dans les gestionnaires d'acteurs, un paramètre peut s'<em>appeler</em> <code>self</code> ; c'est un nom choisi par l'auteur, pas un mot-clé.)"),
            ("Integers do not grow forever", "Les entiers ne grandissent pas indéfiniment",
             "<code>Int</code> is 64 bits and overflow panics rather than promoting. <code>Float</code> follows IEEE 754.",
             "<code>Int</code> fait 64 bits et le débordement panique au lieu de promouvoir. <code>Float</code> suit IEEE 754."),
            ("Reference counting, like CPython", "Comptage de références, comme CPython",
             "Same model, same blind spot: a cycle. CPython adds a collector; Keal asks you to write <code>weak</code> on the back edge, and explains why in its memory document.",
             "Même modèle, même angle mort : le cycle. CPython ajoute un ramasse-miettes ; Keal vous demande d'écrire <code>weak</code> sur l'arête arrière, et explique pourquoi dans son document mémoire."),
        ],
    },
    # ---------------------------------------------------------- JavaScript
    {
        "key": "javascript", "name": "JavaScript", "blurb_en": "No coercions, no undefined, no second equality.",
        "blurb_fr": "Ni coercitions, ni undefined, ni seconde égalité.",
        "intro_en": "If you have written TypeScript, the type annotations will feel familiar — but they are not erased: they compile to layouts and to native code. And the surprises JavaScript keeps are all gone: one equality, no coercion, no <code>undefined</code>, no <code>this</code> that changes meaning by call site.",
        "intro_fr": "Si vous avez écrit du TypeScript, les annotations vous sembleront familières — mais elles ne sont pas effacées : elles compilent en dispositions mémoire et en code natif. Et les surprises que garde JavaScript ont disparu : une seule égalité, pas de coercition, pas d'<code>undefined</code>, pas de <code>this</code> qui change de sens selon l'appel.",
        "rows": [
            ("Binding", "Liaison", "const x = 1", "val x = 1"),
            ("Mutable", "Mutable", "let x = 1", "var x = 1"),
            ("Function", "Fonction", "function add(a, b) { return a + b }", "func add(a: Int, b: Int): Int { a + b }"),
            ("Arrow", "Flèche", "xs.map(x => x * 2)", "xs.map({ it * 2 })"),
            ("Array", "Tableau", "[1, 2]", "[1, 2]"),
            ("Object / Map", "Objet / Map", "new Map([[\"a\", 1]])", "{\"a\": 1}"),
            ("Template literal", "Littéral gabarit", "`hello ${name}`", "\"hello ${name}\""),
            ("Null check", "Test de nullité", "x ?? \"d\"", "x ?: \"d\""),
            ("Optional chain", "Chaînage optionnel", "x?.length", "x?.length"),
            ("Class", "Classe", "class C { constructor(n) { } }", "class C(var n: Int)"),
            ("Promise", "Promise", "await f()", "actors: spawn / send / run"),
        ],
        "notes": [
            ("One equality, and no coercion", "Une seule égalité, sans coercition",
             "<code>==</code> compares values of the same type; there is no <code>===</code> because there is nothing to distinguish it from. <code>\"1\" + 1</code> does not silently become a string of digits — although <code>\"n = \" + n</code> is allowed and renders the value.",
             "<code>==</code> compare des valeurs de même type ; il n'y a pas de <code>===</code> parce qu'il n'y a rien dont le distinguer. <code>\"1\" + 1</code> ne devient pas silencieusement une chaîne — bien que <code>\"n = \" + n</code> soit permis et rende la valeur."),
            ("null exists, undefined does not", "null existe, undefined non",
             "One absent value, in the type or not at all. A missing map key gives <code>null</code>, and the checker makes you handle it.",
             "Une seule valeur absente, dans le type ou pas du tout. Une clé de map absente donne <code>null</code>, et le vérificateur vous oblige à la traiter."),
            ("this is lexical and always the object", "this est lexical et toujours l'objet",
             "Inside a method, <code>this</code> is the instance. It cannot be rebound, lost in a callback, or shadowed by an arrow function.",
             "Dans une méthode, <code>this</code> est l'instance. Il ne peut être relié, perdu dans un callback, ni masqué par une fonction fléchée."),
            ("It compiles to a binary", "Cela compile en binaire",
             "There is no bundler and no runtime to ship: <code>keal build</code> emits C11 and hands it to a C compiler.",
             "Il n'y a ni bundler ni runtime à livrer : <code>keal build</code> émet du C11 et le confie à un compilateur C."),
        ],
    },
]
