//! `keal bindgen header.h` — C prototypes in, `extern fun` declarations out.
//!
//! The mapping is deliberately exact: only types whose ABI Keal can promise
//! are bound — `int64_t`/`long long`, `double`, `bool`, `const char*` as
//! `borrow String`, a returned `char*` as `own String`, and `Keal_Name`
//! mirror structs as their records. Everything else is **skipped with the
//! reason printed**, because a guessed binding is a crash with a delay.
//!
//! This is what makes the Rust and Go paths mechanical: `cbindgen` and
//! `go build -buildmode=c-archive` both produce headers this reads.

use std::process::ExitCode;

pub fn run(path: &str) -> ExitCode {
    let text = match std::fs::read_to_string(path) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("error: cannot read `{}`: {}", path, e);
            return ExitCode::FAILURE;
        }
    };
    print!("{}", generate(path, &text));
    ExitCode::SUCCESS
}

pub fn generate(path: &str, header: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by `keal bindgen {}`. Review before trusting: only what\n\
         // crosses the boundary exactly is bound; anything else is skipped\n\
         // below, with the reason. The header itself still has to be visible\n\
         // to the C compiler — pass `-I...` to `keal build` if it is not.\n\n\
         native \"#include \\\"{}\\\"\"\n",
        path, path
    ));

    for decl in declarations(header) {
        match bind(&decl) {
            Bound::Fun(line) => {
                out.push('\n');
                out.push_str(&line);
                out.push('\n');
            }
            Bound::Skipped(name, reason) => {
                out.push('\n');
                out.push_str(&format!("// skipped {}: {}\n", name, reason));
            }
            Bound::Ignored => {}
        }
    }
    out
}

enum Bound {
    Fun(String),
    Skipped(String, String),
    /// Not a function at all — a typedef, a struct, a variable.
    Ignored,
}

/// Top-level declarations, comments and preprocessor lines removed, brace
/// bodies skipped.
fn declarations(text: &str) -> Vec<String> {
    let stripped = strip_comments(text);
    let no_pp: String = {
        // Preprocessor lines go, honouring `\` continuations.
        let mut out = String::new();
        let mut in_pp = false;
        for line in stripped.lines() {
            let starts_pp = line.trim_start().starts_with('#');
            let continued = in_pp;
            in_pp = (starts_pp || continued) && line.trim_end().ends_with('\\');
            if starts_pp || continued {
                continue;
            }
            out.push_str(line);
            out.push('\n');
        }
        out
    };

    let mut decls = Vec::new();
    let mut buf = String::new();
    let mut depth = 0usize;
    let mut had_body = false;
    for c in no_pp.chars() {
        match c {
            '{' => {
                depth += 1;
            }
            '}' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    had_body = true;
                }
            }
            ';' if depth == 0 => {
                let d = buf.trim().to_string();
                // A body at top level was a definition or a struct; the
                // text around it is not a prototype.
                if !d.is_empty() && !had_body {
                    decls.push(d);
                }
                buf.clear();
                had_body = false;
            }
            _ if depth == 0 => buf.push(c),
            _ => {}
        }
    }
    decls
}

fn strip_comments(text: &str) -> String {
    let bytes: Vec<char> = text.chars().collect();
    let mut out = String::new();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == '/' && i + 1 < bytes.len() && bytes[i + 1] == '/' {
            while i < bytes.len() && bytes[i] != '\n' {
                i += 1;
            }
        } else if bytes[i] == '/' && i + 1 < bytes.len() && bytes[i + 1] == '*' {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == '*' && bytes[i + 1] == '/') {
                i += 1;
            }
            i += 2;
            out.push(' ');
        } else if bytes[i] == '"' {
            // A string literal passes through opaque, so a `;` inside one
            // cannot end a declaration.
            out.push('"');
            i += 1;
            while i < bytes.len() && bytes[i] != '"' {
                if bytes[i] == '\\' {
                    i += 1;
                }
                i += 1;
            }
            out.push('"');
            i += 1;
        } else {
            out.push(bytes[i]);
            i += 1;
        }
    }
    out
}

/// Splits a declaration into identifier-and-punctuation tokens.
fn tokenize(s: &str) -> Vec<String> {
    let mut toks = Vec::new();
    let mut cur = String::new();
    for c in s.chars() {
        if c.is_alphanumeric() || c == '_' {
            cur.push(c);
        } else {
            if !cur.is_empty() {
                toks.push(std::mem::take(&mut cur));
            }
            if !c.is_whitespace() {
                toks.push(c.to_string());
            }
        }
    }
    if !cur.is_empty() {
        toks.push(cur);
    }
    toks
}

const KEAL_KEYWORDS: &[&str] = &[
    "val", "var", "fun", "proc", "class", "if", "else", "unless", "when", "is", "in", "for",
    "while", "return", "break", "continue", "null", "true", "false", "this", "import", "not",
    "and", "or", "xor", "xnor", "nand", "nor", "implies", "borrow", "own",
];

fn bind(decl: &str) -> Bound {
    let toks = tokenize(decl);
    if toks.is_empty() {
        return Bound::Ignored;
    }
    match toks[0].as_str() {
        "typedef" | "struct" | "enum" | "union" => return Bound::Ignored,
        _ => {}
    }
    let Some(open) = toks.iter().position(|t| t == "(") else {
        return Bound::Ignored; // a variable, not a function
    };
    let Some(close) = toks.iter().rposition(|t| t == ")") else {
        return Bound::Ignored;
    };
    if open < 2 || close != toks.len() - 1 {
        return Bound::Ignored;
    }

    let mut head: Vec<&str> = toks[..open].iter().map(|s| s.as_str()).collect();
    if head.first() == Some(&"extern") {
        head.remove(0);
    }
    let name = head.pop().unwrap_or("").to_string();
    if name.is_empty() || !name.chars().next().map(char::is_alphabetic).unwrap_or(false) {
        return Bound::Ignored;
    }
    if head.contains(&"static") || head.contains(&"inline") {
        return Bound::Skipped(name, "static or inline, so there is no symbol to link".into());
    }
    if KEAL_KEYWORDS.contains(&name.as_str()) {
        return Bound::Skipped(name, "its name is a Keal keyword".into());
    }

    let inner = &toks[open + 1..close];
    if inner.iter().count() >= 3 && decl.contains("...") {
        return Bound::Skipped(name, "variadic functions do not cross".into());
    }
    if inner.iter().filter(|t| *t == "(").count() > 0 {
        return Bound::Skipped(
            name,
            "a function-pointer parameter needs the callback story (docs/interop.md, 1d)".into(),
        );
    }

    // The return type.
    let ret = match map_type(&head, true) {
        Ok(r) => r,
        Err(reason) => return Bound::Skipped(name, reason),
    };

    // The parameters: top-level comma split.
    let mut params: Vec<Vec<&str>> = Vec::new();
    let mut cur: Vec<&str> = Vec::new();
    for t in inner {
        if t == "," {
            params.push(std::mem::take(&mut cur));
        } else {
            cur.push(t.as_str());
        }
    }
    if !cur.is_empty() {
        params.push(cur);
    }
    if params.len() == 1 && params[0] == ["void"] {
        params.clear();
    }

    let mut rendered = Vec::new();
    for (i, p) in params.iter().enumerate() {
        let mut ty: Vec<&str> = p.clone();
        // A trailing identifier that is not part of the type is the name.
        let pname = match ty.last() {
            Some(last)
                if ty.len() > 1
                    && last.chars().next().map(|c| c.is_alphabetic() || c == '_').unwrap_or(false)
                    && !matches!(
                        *last,
                        "int" | "char" | "long" | "double" | "bool" | "_Bool" | "void" | "const"
                            | "unsigned" | "signed" | "float" | "int64_t" | "int32_t"
                            | "uint64_t" | "uint32_t" | "size_t"
                    )
                    && !last.starts_with("Keal_") =>
            {
                let n = (*last).to_string();
                ty.pop();
                n
            }
            _ => format!("arg{}", i),
        };
        let pname = if KEAL_KEYWORDS.contains(&pname.as_str()) {
            format!("{}_", pname)
        } else {
            pname
        };
        match map_type(&ty, false) {
            Ok(Some(t)) => rendered.push(format!("{}: {}", pname, t)),
            Ok(None) => {
                return Bound::Skipped(name, "a `void` parameter is not a parameter".into())
            }
            Err(reason) => return Bound::Skipped(name, reason),
        }
    }

    let ret_part = match ret {
        Some(t) => format!(": {}", t),
        None => ": Unit".to_string(),
    };
    Bound::Fun(format!("extern fun {}({}){}", name, rendered.join(", "), ret_part))
}

/// The Keal spelling of a C type, `Ok(None)` for `void`, or the reason it
/// cannot cross. `ret` position allows `char*` (adopted) and forbids
/// `const char*`; parameters are the other way around.
fn map_type(toks: &[&str], ret: bool) -> Result<Option<String>, String> {
    let t: Vec<&str> = toks.to_vec();
    let joined = t.join(" ");
    match t.as_slice() {
        ["void"] => Ok(None),
        ["int64_t"] | ["long", "long"] | ["long", "long", "int"] | ["signed", "long", "long"] => {
            Ok(Some("Int".into()))
        }
        ["double"] => Ok(Some("Float".into())),
        ["bool"] | ["_Bool"] => Ok(Some("Bool".into())),
        ["const", "char", "*"] | ["char", "const", "*"] => {
            if ret {
                Err("returns `const char*`, borrowed text Keal must not adopt; \
                     wrap it in a function returning a malloc'd copy"
                    .into())
            } else {
                Ok(Some("borrow String".into()))
            }
        }
        ["char", "*"] => {
            if ret {
                Ok(Some("own String".into()))
            } else {
                Err("takes `char*`, a mutable buffer Keal cannot promise; \
                     take `const char*` and return the result instead"
                    .into())
            }
        }
        [one] if one.starts_with("Keal_") => Ok(Some(one["Keal_".len()..].to_string())),
        ["int"] | ["int32_t"] | ["unsigned", ..] | ["uint64_t"] | ["uint32_t"] | ["size_t"] => {
            Err(format!(
                "`{}` is not exactly an `int64_t`; wrap it in a function that takes and returns int64_t",
                joined
            ))
        }
        ["float"] => Err("C `float` is 32-bit; take and return `double`".into()),
        _ => Err(format!("`{}` does not cross the boundary", joined)),
    }
}
